[features]
web_search_request = true

[mcp_servers.context7]
command = "npx"
args = [ "-y", "@upstash/context7-mcp" ]

[mcp_servers.shadcn]
command = "npx"
args = [ "shadcn@latest", "mcp" ]

[mcp_servers.better-auth]
command = "npx"
args = [
  "-y",
  "mcp-remote@latest",
  "https://mcp.chonkie.ai/better-auth/better-auth-builder/mcp"
]
