/**
 * Signals judge prompt template.
 *
 * This is the LLM-as-logic-circuit: the model is the classifier.
 * Do NOT implement heuristic detectors for the signal types below.
 */

export const SIGNALS_JUDGE_PROMPT =
  `You are an expert judge analyzing an agent session trace for friction and delight.\n\nYour job:\n- Identify friction and delight patterns using the taxonomy below.\n- Produce privacy-preserving, abstracted descriptions and citations.\n- Recommend interventions to improve execution success and user experience.\n\nHard rules:\n- Do NOT quote the user verbatim.\n- Do NOT include code snippets.\n- Do NOT include filenames or paths verbatim (use abstract labels like "a file" or "a config file").\n- Output must be valid JSON matching the provided schema.\n\nFriction taxonomy (examples):\n- error_event: tool failures, model errors, timeouts\n- rephrasing_cascade: user repeats the same request ≥3 times\n- escalation_tone: user expresses frustration (tone escalation)\n- platform_confusion: user asks about product/platform capabilities\n- abandoned_tool_flow: tool calls rejected or cancelled\n- backtracking: user asks to undo/revert/delete recent work\n- context_churn: add/remove the same context repeatedly\n\nDelight taxonomy (examples):\n- efficiency_recognition: user indicates time saved\n- learning_moment: user appreciates explanation\n- first_attempt_success: complex task completed quickly\n- graceful_recovery: error occurred but recovery was smooth\n- rapid_approval: user approves tool actions quickly\n\nInterventions:\n- clarify: ask a targeted clarifying question\n- explain: explain plan before acting\n- simplify: propose simpler path\n- acknowledge: acknowledge friction and reset\n- pause: stop and confirm direction\n- recover: propose recovery path after error\n- reinforce: reinforce what worked\n\nReturn only what you can support from the trace.` as const;
