// AgentFS Domain Module
// Content-addressed storage and retention management for AgentFS

export type {
  AgeBasis,
  AgeDetails,
  AuditAction,
  AuditLogEntry,
  AuditLogResult,
  AutopinDetails,
  BatchDeleteResult,
  BatchExportResult,
  BatchItemResult,
  BatchPinResult,
  BatchUnpinResult,
  CasArchiveInfo,
  CasCleanupContext,
  CasEntry,
  CasListResult,
  CasRetentionPolicy,
  CasStorageMetrics,
  CleanupContext,
  CleanupNowResult,
  CleanupResult,
  FileSearchResult,
  KeepDetails,
  KvSearchResult,
  OrphanedDetails,
  ProjectStorageMetrics,
  QuarantineEntry,
  QuarantineReason,
  QuarantineRestoreRequest,
  QuarantineRestoreResult,
  QuarantineType,
  RetentionAutopinItem,
  RetentionDecision,
  RetentionDetails,
  RetentionPolicy,
  RetentionPreview,
  RetentionPreviewItem,
  RunEntry,
  RunStorageMetrics,
  SizeCapDetails,
  StorageMetrics,
  ToolCallSearchResult,
} from "./domain";

export {
  calculateCutoffMs,
  checkCasSizeCap,
  checkRunSizeCap,
  decideCasRetention,
  decideRunRetention,
  evaluateCasBatch,
  evaluateRunBatch,
  parseCasMaxBytes,
  parseCasRetentionDays,
  parseMaxBytes,
  parseRetentionDays,
  shouldAutopinFailures,
  shouldDryRunCleanup,
  sortCasByPriority,
  sortRunsByAge,
} from "./policy";
