/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as RemindRouteImport } from './routes/remind'
import { Route as NoteRouteImport } from './routes/note'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSplatRouteImport } from './routes/api/ai/$'
import { Route as OrchestratorRunRouteImport } from './routes/orchestrator/run'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HealthzDepsRouteImport } from './routes/healthz/deps'
import { Route as ApiJwksRouteImport } from './routes/api/jwks'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindRoute = RemindRouteImport.update({
  id: '/remind',
  path: '/remind',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteRoute = NoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSplatRoute = ApiAiSplatRouteImport.update({
  id: '/api/ai/$',
  path: '/api/ai/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRunRoute = OrchestratorRunRouteImport.update({
  id: '/orchestrator/run',
  path: '/orchestrator/run',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzDepsRoute = HealthzDepsRouteImport.update({
  id: '/healthz/deps',
  path: '/healthz/deps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJwksRoute = ApiJwksRouteImport.update({
  id: '/api/jwks',
  path: '/api/jwks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/drive': typeof DriveRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/note': typeof NoteRoute
  '/remind': typeof RemindRoute
  '/todos': typeof TodosRoute
  '/orchestrator/run': typeof OrchestratorRunRoute
  '/healthz': typeof HealthzRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/jwks': typeof ApiJwksRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/drive': typeof DriveRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/note': typeof NoteRoute
  '/remind': typeof RemindRoute
  '/todos': typeof TodosRoute
  '/orchestrator/run': typeof OrchestratorRunRoute
  '/healthz': typeof HealthzRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/jwks': typeof ApiJwksRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/drive': typeof DriveRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/note': typeof NoteRoute
  '/remind': typeof RemindRoute
  '/todos': typeof TodosRoute
  '/orchestrator/run': typeof OrchestratorRunRoute
  '/healthz': typeof HealthzRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/jwks': typeof ApiJwksRoute
  '/api/ai/$': typeof ApiAiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/drive'
    | '/dashboard'
    | '/deployments'
    | '/login'
    | '/note'
    | '/remind'
    | '/todos'
    | '/orchestrator/run'
    | '/healthz'
    | '/healthz/deps'
    | '/api/metrics'
    | '/api/jwks'
    | '/api/ai/$'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/drive'
    | '/dashboard'
    | '/deployments'
    | '/login'
    | '/note'
    | '/remind'
    | '/todos'
    | '/orchestrator/run'
    | '/healthz'
    | '/healthz/deps'
    | '/api/metrics'
    | '/api/jwks'
    | '/api/ai/$'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/drive'
    | '/dashboard'
    | '/deployments'
    | '/login'
    | '/note'
    | '/remind'
    | '/todos'
    | '/orchestrator/run'
    | '/healthz'
    | '/healthz/deps'
    | '/api/metrics'
    | '/api/jwks'
    | '/api/ai/$'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DriveRoute: typeof DriveRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NoteRoute: typeof NoteRoute
  RemindRoute: typeof RemindRoute
  TodosRoute: typeof TodosRoute
  OrchestratorRunRoute: typeof OrchestratorRunRoute
  HealthzRoute: typeof HealthzRoute
  HealthzDepsRoute: typeof HealthzDepsRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiJwksRoute: typeof ApiJwksRoute
  ApiAiSplatRoute: typeof ApiAiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remind': {
      id: '/remind'
      path: '/remind'
      fullPath: '/remind'
      preLoaderRoute: typeof RemindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator/run': {
      id: '/orchestrator/run'
      path: '/orchestrator/run'
      fullPath: '/orchestrator/run'
      preLoaderRoute: typeof OrchestratorRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz/deps': {
      id: '/healthz/deps'
      path: '/healthz/deps'
      fullPath: '/healthz/deps'
      preLoaderRoute: typeof HealthzDepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jwks': {
      id: '/api/jwks'
      path: '/api/jwks'
      fullPath: '/api/jwks'
      preLoaderRoute: typeof ApiJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$': {
      id: '/api/ai/$'
      path: '/api/ai/$'
      fullPath: '/api/ai/$'
      preLoaderRoute: typeof ApiAiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DriveRoute: DriveRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NoteRoute: NoteRoute,
  RemindRoute: RemindRoute,
  TodosRoute: TodosRoute,
  OrchestratorRunRoute: OrchestratorRunRoute,
  HealthzRoute: HealthzRoute,
  HealthzDepsRoute: HealthzDepsRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiJwksRoute: ApiJwksRoute,
  ApiAiSplatRoute: ApiAiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
