/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceS2sRouteImport } from './routes/voice-s2s'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MindscapeRouteImport } from './routes/mindscape'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowRunIdRouteImport } from './routes/workflow.$runId'
import { Route as HealthzDepsRouteImport } from './routes/healthz/deps'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiJwksRouteImport } from './routes/api/jwks'
import { Route as AuthCallbackLinearRouteImport } from './routes/auth/callback/linear'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiOrchestratorSplatRouteImport } from './routes/api/orchestrator/$'
import { Route as ApiLinearWebhookRouteImport } from './routes/api/linear/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssistantSplatRouteImport } from './routes/api/assistant/$'

const VoiceS2sRoute = VoiceS2sRouteImport.update({
  id: '/voice-s2s',
  path: '/voice-s2s',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MindscapeRoute = MindscapeRouteImport.update({
  id: '/mindscape',
  path: '/mindscape',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRunIdRoute = WorkflowRunIdRouteImport.update({
  id: '/workflow/$runId',
  path: '/workflow/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzDepsRoute = HealthzDepsRouteImport.update({
  id: '/deps',
  path: '/deps',
  getParentRoute: () => HealthzRoute,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJwksRoute = ApiJwksRouteImport.update({
  id: '/api/jwks',
  path: '/api/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackLinearRoute = AuthCallbackLinearRouteImport.update({
  id: '/auth/callback/linear',
  path: '/auth/callback/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestratorSplatRoute = ApiOrchestratorSplatRouteImport.update({
  id: '/api/orchestrator/$',
  path: '/api/orchestrator/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinearWebhookRoute = ApiLinearWebhookRouteImport.update({
  id: '/api/linear/webhook',
  path: '/api/linear/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantSplatRoute = ApiAssistantSplatRouteImport.update({
  id: '/api/assistant/$',
  path: '/api/assistant/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/healthz': typeof HealthzRouteWithChildren
  '/login': typeof LoginRoute
  '/mindscape': typeof MindscapeRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/voice-s2s': typeof VoiceS2sRoute
  '/api/jwks': typeof ApiJwksRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/workflow/$runId': typeof WorkflowRunIdRoute
  '/api/assistant/$': typeof ApiAssistantSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/linear/webhook': typeof ApiLinearWebhookRoute
  '/api/orchestrator/$': typeof ApiOrchestratorSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/callback/linear': typeof AuthCallbackLinearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/healthz': typeof HealthzRouteWithChildren
  '/login': typeof LoginRoute
  '/mindscape': typeof MindscapeRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/voice-s2s': typeof VoiceS2sRoute
  '/api/jwks': typeof ApiJwksRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/workflow/$runId': typeof WorkflowRunIdRoute
  '/api/assistant/$': typeof ApiAssistantSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/linear/webhook': typeof ApiLinearWebhookRoute
  '/api/orchestrator/$': typeof ApiOrchestratorSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/callback/linear': typeof AuthCallbackLinearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive': typeof DriveRoute
  '/healthz': typeof HealthzRouteWithChildren
  '/login': typeof LoginRoute
  '/mindscape': typeof MindscapeRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/voice-s2s': typeof VoiceS2sRoute
  '/api/jwks': typeof ApiJwksRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/workflow/$runId': typeof WorkflowRunIdRoute
  '/api/assistant/$': typeof ApiAssistantSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/linear/webhook': typeof ApiLinearWebhookRoute
  '/api/orchestrator/$': typeof ApiOrchestratorSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/callback/linear': typeof AuthCallbackLinearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drive'
    | '/healthz'
    | '/login'
    | '/mindscape'
    | '/onboarding'
    | '/settings'
    | '/voice-s2s'
    | '/api/jwks'
    | '/api/metrics'
    | '/healthz/deps'
    | '/workflow/$runId'
    | '/api/assistant/$'
    | '/api/auth/$'
    | '/api/linear/webhook'
    | '/api/orchestrator/$'
    | '/api/trpc/$'
    | '/auth/callback/linear'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drive'
    | '/healthz'
    | '/login'
    | '/mindscape'
    | '/onboarding'
    | '/settings'
    | '/voice-s2s'
    | '/api/jwks'
    | '/api/metrics'
    | '/healthz/deps'
    | '/workflow/$runId'
    | '/api/assistant/$'
    | '/api/auth/$'
    | '/api/linear/webhook'
    | '/api/orchestrator/$'
    | '/api/trpc/$'
    | '/auth/callback/linear'
  id:
    | '__root__'
    | '/'
    | '/drive'
    | '/healthz'
    | '/login'
    | '/mindscape'
    | '/onboarding'
    | '/settings'
    | '/voice-s2s'
    | '/api/jwks'
    | '/api/metrics'
    | '/healthz/deps'
    | '/workflow/$runId'
    | '/api/assistant/$'
    | '/api/auth/$'
    | '/api/linear/webhook'
    | '/api/orchestrator/$'
    | '/api/trpc/$'
    | '/auth/callback/linear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveRoute: typeof DriveRoute
  HealthzRoute: typeof HealthzRouteWithChildren
  LoginRoute: typeof LoginRoute
  MindscapeRoute: typeof MindscapeRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  VoiceS2sRoute: typeof VoiceS2sRoute
  ApiJwksRoute: typeof ApiJwksRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  WorkflowRunIdRoute: typeof WorkflowRunIdRoute
  ApiAssistantSplatRoute: typeof ApiAssistantSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLinearWebhookRoute: typeof ApiLinearWebhookRoute
  ApiOrchestratorSplatRoute: typeof ApiOrchestratorSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  AuthCallbackLinearRoute: typeof AuthCallbackLinearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-s2s': {
      id: '/voice-s2s'
      path: '/voice-s2s'
      fullPath: '/voice-s2s'
      preLoaderRoute: typeof VoiceS2sRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindscape': {
      id: '/mindscape'
      path: '/mindscape'
      fullPath: '/mindscape'
      preLoaderRoute: typeof MindscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$runId': {
      id: '/workflow/$runId'
      path: '/workflow/$runId'
      fullPath: '/workflow/$runId'
      preLoaderRoute: typeof WorkflowRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz/deps': {
      id: '/healthz/deps'
      path: '/deps'
      fullPath: '/healthz/deps'
      preLoaderRoute: typeof HealthzDepsRouteImport
      parentRoute: typeof HealthzRoute
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jwks': {
      id: '/api/jwks'
      path: '/api/jwks'
      fullPath: '/api/jwks'
      preLoaderRoute: typeof ApiJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/linear': {
      id: '/auth/callback/linear'
      path: '/auth/callback/linear'
      fullPath: '/auth/callback/linear'
      preLoaderRoute: typeof AuthCallbackLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrator/$': {
      id: '/api/orchestrator/$'
      path: '/api/orchestrator/$'
      fullPath: '/api/orchestrator/$'
      preLoaderRoute: typeof ApiOrchestratorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linear/webhook': {
      id: '/api/linear/webhook'
      path: '/api/linear/webhook'
      fullPath: '/api/linear/webhook'
      preLoaderRoute: typeof ApiLinearWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/$': {
      id: '/api/assistant/$'
      path: '/api/assistant/$'
      fullPath: '/api/assistant/$'
      preLoaderRoute: typeof ApiAssistantSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HealthzRouteChildren {
  HealthzDepsRoute: typeof HealthzDepsRoute
}

const HealthzRouteChildren: HealthzRouteChildren = {
  HealthzDepsRoute: HealthzDepsRoute,
}

const HealthzRouteWithChildren =
  HealthzRoute._addFileChildren(HealthzRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveRoute: DriveRoute,
  HealthzRoute: HealthzRouteWithChildren,
  LoginRoute: LoginRoute,
  MindscapeRoute: MindscapeRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  VoiceS2sRoute: VoiceS2sRoute,
  ApiJwksRoute: ApiJwksRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  WorkflowRunIdRoute: WorkflowRunIdRoute,
  ApiAssistantSplatRoute: ApiAssistantSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLinearWebhookRoute: ApiLinearWebhookRoute,
  ApiOrchestratorSplatRoute: ApiOrchestratorSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  AuthCallbackLinearRoute: AuthCallbackLinearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
