/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ElevateRouteImport } from './routes/elevate'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as HealthzEmbedRouteImport } from './routes/healthz/embed'
import { Route as HealthzDepsRouteImport } from './routes/healthz/deps'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOrchestratorRouteImport } from './routes/api/orchestrator'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ProtectedVoiceS2sRouteImport } from './routes/_protected/voice-s2s'
import { Route as ProtectedTimerRouteImport } from './routes/_protected/timer'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDriveRouteImport } from './routes/_protected/drive'
import { Route as ProtectedComponentsRouteImport } from './routes/_protected/components'
import { Route as ProtectedBookRouteImport } from './routes/_protected/book'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as AuthCallbackLinearRouteImport } from './routes/auth/callback/linear'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiOrchestratorSplatRouteImport } from './routes/api/orchestrator/$'
import { Route as ApiLinearWebhookRouteImport } from './routes/api/linear/webhook'
import { Route as ApiDesktopMetricsRouteImport } from './routes/api/desktop.metrics'
import { Route as ApiConversationSplatRouteImport } from './routes/api/conversation/$'
import { Route as ApiAuthRevokeRouteImport } from './routes/api/auth/revoke'
import { Route as ApiAuthIntrospectRouteImport } from './routes/api/auth/introspect'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssistantSplatRouteImport } from './routes/api/assistant/$'
import { Route as ProtectedWorkflowRunIdRouteImport } from './routes/_protected/workflow.$runId'
import { Route as ProtectedSettingsVisualRouteImport } from './routes/_protected/settings/visual'
import { Route as ProtectedSettingsProfileRouteImport } from './routes/_protected/settings/profile'
import { Route as ProtectedSettingsPrivacyRouteImport } from './routes/_protected/settings/privacy'
import { Route as ProtectedSettingsModelsRouteImport } from './routes/_protected/settings/models'
import { Route as ProtectedSettingsMcpRouteImport } from './routes/_protected/settings/mcp'
import { Route as ProtectedExperimentalTuneRouteImport } from './routes/_protected/experimental/tune'
import { Route as ProtectedComponentsNameRouteImport } from './routes/_protected/components.$name'
import { Route as ProtectedAdminVoiceTableRouteImport } from './routes/_protected/admin/voice-table'
import { Route as ProtectedAdminVoiceRouteImport } from './routes/_protected/admin/voice'
import { Route as ProtectedAdminMetricsRouteImport } from './routes/_protected/admin/metrics'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevateRoute = ElevateRouteImport.update({
  id: '/elevate',
  path: '/elevate',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const HealthzEmbedRoute = HealthzEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => HealthzRoute,
} as any)
const HealthzDepsRoute = HealthzDepsRouteImport.update({
  id: '/deps',
  path: '/deps',
  getParentRoute: () => HealthzRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestratorRoute = ApiOrchestratorRouteImport.update({
  id: '/api/orchestrator',
  path: '/api/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedVoiceS2sRoute = ProtectedVoiceS2sRouteImport.update({
  id: '/voice-s2s',
  path: '/voice-s2s',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTimerRoute = ProtectedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriveRoute = ProtectedDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedComponentsRoute = ProtectedComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBookRoute = ProtectedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const AuthCallbackLinearRoute = AuthCallbackLinearRouteImport.update({
  id: '/auth/callback/linear',
  path: '/auth/callback/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestratorSplatRoute = ApiOrchestratorSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiOrchestratorRoute,
} as any)
const ApiLinearWebhookRoute = ApiLinearWebhookRouteImport.update({
  id: '/api/linear/webhook',
  path: '/api/linear/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopMetricsRoute = ApiDesktopMetricsRouteImport.update({
  id: '/api/desktop/metrics',
  path: '/api/desktop/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationSplatRoute = ApiConversationSplatRouteImport.update({
  id: '/api/conversation/$',
  path: '/api/conversation/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRevokeRoute = ApiAuthRevokeRouteImport.update({
  id: '/api/auth/revoke',
  path: '/api/auth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthIntrospectRoute = ApiAuthIntrospectRouteImport.update({
  id: '/api/auth/introspect',
  path: '/api/auth/introspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantSplatRoute = ApiAssistantSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAssistantRoute,
} as any)
const ProtectedWorkflowRunIdRoute = ProtectedWorkflowRunIdRouteImport.update({
  id: '/workflow/$runId',
  path: '/workflow/$runId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsVisualRoute = ProtectedSettingsVisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsProfileRoute =
  ProtectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsPrivacyRoute =
  ProtectedSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsModelsRoute = ProtectedSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsMcpRoute = ProtectedSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedExperimentalTuneRoute =
  ProtectedExperimentalTuneRouteImport.update({
    id: '/experimental/tune',
    path: '/experimental/tune',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedComponentsNameRoute = ProtectedComponentsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ProtectedComponentsRoute,
} as any)
const ProtectedAdminVoiceTableRoute =
  ProtectedAdminVoiceTableRouteImport.update({
    id: '/voice-table',
    path: '/voice-table',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminVoiceRoute = ProtectedAdminVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminMetricsRoute = ProtectedAdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ProtectedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/elevate': typeof ElevateRoute
  '/healthz': typeof HealthzRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/book': typeof ProtectedBookRoute
  '/components': typeof ProtectedComponentsRouteWithChildren
  '/drive': typeof ProtectedDriveRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/timer': typeof ProtectedTimerRoute
  '/voice-s2s': typeof ProtectedVoiceS2sRoute
  '/api/assistant': typeof ApiAssistantRouteWithChildren
  '/api/metrics': typeof ApiMetricsRoute
  '/api/orchestrator': typeof ApiOrchestratorRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/healthz/embed': typeof HealthzEmbedRoute
  '/': typeof ProtectedIndexRoute
  '/admin/metrics': typeof ProtectedAdminMetricsRoute
  '/admin/voice': typeof ProtectedAdminVoiceRoute
  '/admin/voice-table': typeof ProtectedAdminVoiceTableRoute
  '/components/$name': typeof ProtectedComponentsNameRoute
  '/experimental/tune': typeof ProtectedExperimentalTuneRoute
  '/settings/mcp': typeof ProtectedSettingsMcpRoute
  '/settings/models': typeof ProtectedSettingsModelsRoute
  '/settings/privacy': typeof ProtectedSettingsPrivacyRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/visual': typeof ProtectedSettingsVisualRoute
  '/workflow/$runId': typeof ProtectedWorkflowRunIdRoute
  '/api/assistant/$': typeof ApiAssistantSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/introspect': typeof ApiAuthIntrospectRoute
  '/api/auth/revoke': typeof ApiAuthRevokeRoute
  '/api/conversation/$': typeof ApiConversationSplatRoute
  '/api/desktop/metrics': typeof ApiDesktopMetricsRoute
  '/api/linear/webhook': typeof ApiLinearWebhookRoute
  '/api/orchestrator/$': typeof ApiOrchestratorSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/callback/linear': typeof AuthCallbackLinearRoute
  '/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/elevate': typeof ElevateRoute
  '/healthz': typeof HealthzRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/book': typeof ProtectedBookRoute
  '/components': typeof ProtectedComponentsRouteWithChildren
  '/drive': typeof ProtectedDriveRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/timer': typeof ProtectedTimerRoute
  '/voice-s2s': typeof ProtectedVoiceS2sRoute
  '/api/assistant': typeof ApiAssistantRouteWithChildren
  '/api/metrics': typeof ApiMetricsRoute
  '/api/orchestrator': typeof ApiOrchestratorRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/healthz/embed': typeof HealthzEmbedRoute
  '/': typeof ProtectedIndexRoute
  '/admin/metrics': typeof ProtectedAdminMetricsRoute
  '/admin/voice': typeof ProtectedAdminVoiceRoute
  '/admin/voice-table': typeof ProtectedAdminVoiceTableRoute
  '/components/$name': typeof ProtectedComponentsNameRoute
  '/experimental/tune': typeof ProtectedExperimentalTuneRoute
  '/settings/mcp': typeof ProtectedSettingsMcpRoute
  '/settings/models': typeof ProtectedSettingsModelsRoute
  '/settings/privacy': typeof ProtectedSettingsPrivacyRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/visual': typeof ProtectedSettingsVisualRoute
  '/workflow/$runId': typeof ProtectedWorkflowRunIdRoute
  '/api/assistant/$': typeof ApiAssistantSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/introspect': typeof ApiAuthIntrospectRoute
  '/api/auth/revoke': typeof ApiAuthRevokeRoute
  '/api/conversation/$': typeof ApiConversationSplatRoute
  '/api/desktop/metrics': typeof ApiDesktopMetricsRoute
  '/api/linear/webhook': typeof ApiLinearWebhookRoute
  '/api/orchestrator/$': typeof ApiOrchestratorSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/callback/linear': typeof AuthCallbackLinearRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/elevate': typeof ElevateRoute
  '/healthz': typeof HealthzRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/book': typeof ProtectedBookRoute
  '/_protected/components': typeof ProtectedComponentsRouteWithChildren
  '/_protected/drive': typeof ProtectedDriveRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/timer': typeof ProtectedTimerRoute
  '/_protected/voice-s2s': typeof ProtectedVoiceS2sRoute
  '/api/assistant': typeof ApiAssistantRouteWithChildren
  '/api/metrics': typeof ApiMetricsRoute
  '/api/orchestrator': typeof ApiOrchestratorRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/healthz/deps': typeof HealthzDepsRoute
  '/healthz/embed': typeof HealthzEmbedRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/admin/metrics': typeof ProtectedAdminMetricsRoute
  '/_protected/admin/voice': typeof ProtectedAdminVoiceRoute
  '/_protected/admin/voice-table': typeof ProtectedAdminVoiceTableRoute
  '/_protected/components/$name': typeof ProtectedComponentsNameRoute
  '/_protected/experimental/tune': typeof ProtectedExperimentalTuneRoute
  '/_protected/settings/mcp': typeof ProtectedSettingsMcpRoute
  '/_protected/settings/models': typeof ProtectedSettingsModelsRoute
  '/_protected/settings/privacy': typeof ProtectedSettingsPrivacyRoute
  '/_protected/settings/profile': typeof ProtectedSettingsProfileRoute
  '/_protected/settings/visual': typeof ProtectedSettingsVisualRoute
  '/_protected/workflow/$runId': typeof ProtectedWorkflowRunIdRoute
  '/api/assistant/$': typeof ApiAssistantSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/introspect': typeof ApiAuthIntrospectRoute
  '/api/auth/revoke': typeof ApiAuthRevokeRoute
  '/api/conversation/$': typeof ApiConversationSplatRoute
  '/api/desktop/metrics': typeof ApiDesktopMetricsRoute
  '/api/linear/webhook': typeof ApiLinearWebhookRoute
  '/api/orchestrator/$': typeof ApiOrchestratorSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/callback/linear': typeof AuthCallbackLinearRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/consent'
    | '/device'
    | '/elevate'
    | '/healthz'
    | '/login'
    | '/onboarding'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/book'
    | '/components'
    | '/drive'
    | '/settings'
    | '/timer'
    | '/voice-s2s'
    | '/api/assistant'
    | '/api/metrics'
    | '/api/orchestrator'
    | '/api/search'
    | '/docs/$'
    | '/healthz/deps'
    | '/healthz/embed'
    | '/'
    | '/admin/metrics'
    | '/admin/voice'
    | '/admin/voice-table'
    | '/components/$name'
    | '/experimental/tune'
    | '/settings/mcp'
    | '/settings/models'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/visual'
    | '/workflow/$runId'
    | '/api/assistant/$'
    | '/api/auth/$'
    | '/api/auth/introspect'
    | '/api/auth/revoke'
    | '/api/conversation/$'
    | '/api/desktop/metrics'
    | '/api/linear/webhook'
    | '/api/orchestrator/$'
    | '/api/trpc/$'
    | '/auth/callback/linear'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/consent'
    | '/device'
    | '/elevate'
    | '/healthz'
    | '/login'
    | '/onboarding'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/book'
    | '/components'
    | '/drive'
    | '/settings'
    | '/timer'
    | '/voice-s2s'
    | '/api/assistant'
    | '/api/metrics'
    | '/api/orchestrator'
    | '/api/search'
    | '/docs/$'
    | '/healthz/deps'
    | '/healthz/embed'
    | '/'
    | '/admin/metrics'
    | '/admin/voice'
    | '/admin/voice-table'
    | '/components/$name'
    | '/experimental/tune'
    | '/settings/mcp'
    | '/settings/models'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/visual'
    | '/workflow/$runId'
    | '/api/assistant/$'
    | '/api/auth/$'
    | '/api/auth/introspect'
    | '/api/auth/revoke'
    | '/api/conversation/$'
    | '/api/desktop/metrics'
    | '/api/linear/webhook'
    | '/api/orchestrator/$'
    | '/api/trpc/$'
    | '/auth/callback/linear'
    | '/admin'
  id:
    | '__root__'
    | '/_protected'
    | '/consent'
    | '/device'
    | '/elevate'
    | '/healthz'
    | '/login'
    | '/onboarding'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_protected/admin'
    | '/_protected/book'
    | '/_protected/components'
    | '/_protected/drive'
    | '/_protected/settings'
    | '/_protected/timer'
    | '/_protected/voice-s2s'
    | '/api/assistant'
    | '/api/metrics'
    | '/api/orchestrator'
    | '/api/search'
    | '/docs/$'
    | '/healthz/deps'
    | '/healthz/embed'
    | '/_protected/'
    | '/_protected/admin/metrics'
    | '/_protected/admin/voice'
    | '/_protected/admin/voice-table'
    | '/_protected/components/$name'
    | '/_protected/experimental/tune'
    | '/_protected/settings/mcp'
    | '/_protected/settings/models'
    | '/_protected/settings/privacy'
    | '/_protected/settings/profile'
    | '/_protected/settings/visual'
    | '/_protected/workflow/$runId'
    | '/api/assistant/$'
    | '/api/auth/$'
    | '/api/auth/introspect'
    | '/api/auth/revoke'
    | '/api/conversation/$'
    | '/api/desktop/metrics'
    | '/api/linear/webhook'
    | '/api/orchestrator/$'
    | '/api/trpc/$'
    | '/auth/callback/linear'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  DeviceRoute: typeof DeviceRoute
  ElevateRoute: typeof ElevateRoute
  HealthzRoute: typeof HealthzRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiAssistantRoute: typeof ApiAssistantRouteWithChildren
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiOrchestratorRoute: typeof ApiOrchestratorRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthIntrospectRoute: typeof ApiAuthIntrospectRoute
  ApiAuthRevokeRoute: typeof ApiAuthRevokeRoute
  ApiConversationSplatRoute: typeof ApiConversationSplatRoute
  ApiDesktopMetricsRoute: typeof ApiDesktopMetricsRoute
  ApiLinearWebhookRoute: typeof ApiLinearWebhookRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  AuthCallbackLinearRoute: typeof AuthCallbackLinearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elevate': {
      id: '/elevate'
      path: '/elevate'
      fullPath: '/elevate'
      preLoaderRoute: typeof ElevateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/healthz/embed': {
      id: '/healthz/embed'
      path: '/embed'
      fullPath: '/healthz/embed'
      preLoaderRoute: typeof HealthzEmbedRouteImport
      parentRoute: typeof HealthzRoute
    }
    '/healthz/deps': {
      id: '/healthz/deps'
      path: '/deps'
      fullPath: '/healthz/deps'
      preLoaderRoute: typeof HealthzDepsRouteImport
      parentRoute: typeof HealthzRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrator': {
      id: '/api/orchestrator'
      path: '/api/orchestrator'
      fullPath: '/api/orchestrator'
      preLoaderRoute: typeof ApiOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/voice-s2s': {
      id: '/_protected/voice-s2s'
      path: '/voice-s2s'
      fullPath: '/voice-s2s'
      preLoaderRoute: typeof ProtectedVoiceS2sRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/timer': {
      id: '/_protected/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof ProtectedTimerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drive': {
      id: '/_protected/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof ProtectedDriveRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/components': {
      id: '/_protected/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ProtectedComponentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/book': {
      id: '/_protected/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof ProtectedBookRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/auth/callback/linear': {
      id: '/auth/callback/linear'
      path: '/auth/callback/linear'
      fullPath: '/auth/callback/linear'
      preLoaderRoute: typeof AuthCallbackLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrator/$': {
      id: '/api/orchestrator/$'
      path: '/$'
      fullPath: '/api/orchestrator/$'
      preLoaderRoute: typeof ApiOrchestratorSplatRouteImport
      parentRoute: typeof ApiOrchestratorRoute
    }
    '/api/linear/webhook': {
      id: '/api/linear/webhook'
      path: '/api/linear/webhook'
      fullPath: '/api/linear/webhook'
      preLoaderRoute: typeof ApiLinearWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/metrics': {
      id: '/api/desktop/metrics'
      path: '/api/desktop/metrics'
      fullPath: '/api/desktop/metrics'
      preLoaderRoute: typeof ApiDesktopMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation/$': {
      id: '/api/conversation/$'
      path: '/api/conversation/$'
      fullPath: '/api/conversation/$'
      preLoaderRoute: typeof ApiConversationSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/revoke': {
      id: '/api/auth/revoke'
      path: '/api/auth/revoke'
      fullPath: '/api/auth/revoke'
      preLoaderRoute: typeof ApiAuthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/introspect': {
      id: '/api/auth/introspect'
      path: '/api/auth/introspect'
      fullPath: '/api/auth/introspect'
      preLoaderRoute: typeof ApiAuthIntrospectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/$': {
      id: '/api/assistant/$'
      path: '/$'
      fullPath: '/api/assistant/$'
      preLoaderRoute: typeof ApiAssistantSplatRouteImport
      parentRoute: typeof ApiAssistantRoute
    }
    '/_protected/workflow/$runId': {
      id: '/_protected/workflow/$runId'
      path: '/workflow/$runId'
      fullPath: '/workflow/$runId'
      preLoaderRoute: typeof ProtectedWorkflowRunIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/visual': {
      id: '/_protected/settings/visual'
      path: '/visual'
      fullPath: '/settings/visual'
      preLoaderRoute: typeof ProtectedSettingsVisualRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/profile': {
      id: '/_protected/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedSettingsProfileRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/privacy': {
      id: '/_protected/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof ProtectedSettingsPrivacyRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/models': {
      id: '/_protected/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof ProtectedSettingsModelsRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/mcp': {
      id: '/_protected/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof ProtectedSettingsMcpRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/experimental/tune': {
      id: '/_protected/experimental/tune'
      path: '/experimental/tune'
      fullPath: '/experimental/tune'
      preLoaderRoute: typeof ProtectedExperimentalTuneRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/components/$name': {
      id: '/_protected/components/$name'
      path: '/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof ProtectedComponentsNameRouteImport
      parentRoute: typeof ProtectedComponentsRoute
    }
    '/_protected/admin/voice-table': {
      id: '/_protected/admin/voice-table'
      path: '/voice-table'
      fullPath: '/admin/voice-table'
      preLoaderRoute: typeof ProtectedAdminVoiceTableRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/voice': {
      id: '/_protected/admin/voice'
      path: '/voice'
      fullPath: '/admin/voice'
      preLoaderRoute: typeof ProtectedAdminVoiceRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/metrics': {
      id: '/_protected/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof ProtectedAdminMetricsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminMetricsRoute: typeof ProtectedAdminMetricsRoute
  ProtectedAdminVoiceRoute: typeof ProtectedAdminVoiceRoute
  ProtectedAdminVoiceTableRoute: typeof ProtectedAdminVoiceTableRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminMetricsRoute: ProtectedAdminMetricsRoute,
  ProtectedAdminVoiceRoute: ProtectedAdminVoiceRoute,
  ProtectedAdminVoiceTableRoute: ProtectedAdminVoiceTableRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedComponentsRouteChildren {
  ProtectedComponentsNameRoute: typeof ProtectedComponentsNameRoute
}

const ProtectedComponentsRouteChildren: ProtectedComponentsRouteChildren = {
  ProtectedComponentsNameRoute: ProtectedComponentsNameRoute,
}

const ProtectedComponentsRouteWithChildren =
  ProtectedComponentsRoute._addFileChildren(ProtectedComponentsRouteChildren)

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsMcpRoute: typeof ProtectedSettingsMcpRoute
  ProtectedSettingsModelsRoute: typeof ProtectedSettingsModelsRoute
  ProtectedSettingsPrivacyRoute: typeof ProtectedSettingsPrivacyRoute
  ProtectedSettingsProfileRoute: typeof ProtectedSettingsProfileRoute
  ProtectedSettingsVisualRoute: typeof ProtectedSettingsVisualRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsMcpRoute: ProtectedSettingsMcpRoute,
  ProtectedSettingsModelsRoute: ProtectedSettingsModelsRoute,
  ProtectedSettingsPrivacyRoute: ProtectedSettingsPrivacyRoute,
  ProtectedSettingsProfileRoute: ProtectedSettingsProfileRoute,
  ProtectedSettingsVisualRoute: ProtectedSettingsVisualRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedBookRoute: typeof ProtectedBookRoute
  ProtectedComponentsRoute: typeof ProtectedComponentsRouteWithChildren
  ProtectedDriveRoute: typeof ProtectedDriveRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedTimerRoute: typeof ProtectedTimerRoute
  ProtectedVoiceS2sRoute: typeof ProtectedVoiceS2sRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedExperimentalTuneRoute: typeof ProtectedExperimentalTuneRoute
  ProtectedWorkflowRunIdRoute: typeof ProtectedWorkflowRunIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedBookRoute: ProtectedBookRoute,
  ProtectedComponentsRoute: ProtectedComponentsRouteWithChildren,
  ProtectedDriveRoute: ProtectedDriveRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedTimerRoute: ProtectedTimerRoute,
  ProtectedVoiceS2sRoute: ProtectedVoiceS2sRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedExperimentalTuneRoute: ProtectedExperimentalTuneRoute,
  ProtectedWorkflowRunIdRoute: ProtectedWorkflowRunIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface HealthzRouteChildren {
  HealthzDepsRoute: typeof HealthzDepsRoute
  HealthzEmbedRoute: typeof HealthzEmbedRoute
}

const HealthzRouteChildren: HealthzRouteChildren = {
  HealthzDepsRoute: HealthzDepsRoute,
  HealthzEmbedRoute: HealthzEmbedRoute,
}

const HealthzRouteWithChildren =
  HealthzRoute._addFileChildren(HealthzRouteChildren)

interface ApiAssistantRouteChildren {
  ApiAssistantSplatRoute: typeof ApiAssistantSplatRoute
}

const ApiAssistantRouteChildren: ApiAssistantRouteChildren = {
  ApiAssistantSplatRoute: ApiAssistantSplatRoute,
}

const ApiAssistantRouteWithChildren = ApiAssistantRoute._addFileChildren(
  ApiAssistantRouteChildren,
)

interface ApiOrchestratorRouteChildren {
  ApiOrchestratorSplatRoute: typeof ApiOrchestratorSplatRoute
}

const ApiOrchestratorRouteChildren: ApiOrchestratorRouteChildren = {
  ApiOrchestratorSplatRoute: ApiOrchestratorSplatRoute,
}

const ApiOrchestratorRouteWithChildren = ApiOrchestratorRoute._addFileChildren(
  ApiOrchestratorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ConsentRoute: ConsentRoute,
  DeviceRoute: DeviceRoute,
  ElevateRoute: ElevateRoute,
  HealthzRoute: HealthzRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiAssistantRoute: ApiAssistantRouteWithChildren,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiOrchestratorRoute: ApiOrchestratorRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthIntrospectRoute: ApiAuthIntrospectRoute,
  ApiAuthRevokeRoute: ApiAuthRevokeRoute,
  ApiConversationSplatRoute: ApiConversationSplatRoute,
  ApiDesktopMetricsRoute: ApiDesktopMetricsRoute,
  ApiLinearWebhookRoute: ApiLinearWebhookRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  AuthCallbackLinearRoute: AuthCallbackLinearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
