import { createFileRoute } from "@tanstack/react-router";

import { ReviewsDashboard } from "@/components/apps/reviews";

// Route will be properly typed when generated by TanStack Router Vite plugin
// @ts-expect-error - Route path not in routeTree.gen.ts until next build
export const Route = createFileRoute("/_protected/reviews")({
  component: ReviewsPage,
});

function ReviewsPage() {
  return (
    <div className="h-screen">
      <ReviewsDashboard />
    </div>
  );
}
