import { logger } from "@alfred/logger";
import { TRPCError } from "@trpc/server";
import type { WorkflowInputPayload } from "./schema";
import { toolTicket } from "../orchestrator/tool/ticket";

const MAX_LINEAR_TITLE = 240;

export type LinearTicketLink = {
  issueId: string;
  sessionId: string;
  issueUrl?: string;
  created: boolean;
};

function sanitize(value: string | undefined | null): string | undefined {
  if (!value) {
    return undefined;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function buildTitle(requirement: string, override?: string): string {
  const source = sanitize(override) ?? requirement.trim();
  if (source.length <= MAX_LINEAR_TITLE) {
    return source;
  }
  return `${source.slice(0, MAX_LINEAR_TITLE - 3)}...`;
}

function buildDescription(requirement: string, override?: string): string {
  const base: string[] = [];
  if (sanitize(override)) {
    base.push(String(override).trim());
  }
  const trimmedRequirement = requirement.trim();
  if (trimmedRequirement.length > 0) {
    base.push(`**Directive**\n${trimmedRequirement}`);
  }
  if (base.length === 0) {
    base.push("Automated directive generated by ALFRED.");
  }
  return base.join("\n\n");
}

export async function ensureLinearTicket(params: {
  linear?: WorkflowInputPayload["linear"];
  authzLinear?: string;
  requirement: string;
}): Promise<{
  linear?: WorkflowInputPayload["linear"];
  ticket?: LinearTicketLink;
}> {
  const { linear, authzLinear, requirement } = params;
  if (!linear) {
    return { linear: undefined, ticket: undefined };
  }

  const space = sanitize(linear.space);
  if (!space) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "linear_space_required",
    });
  }

  const authz = sanitize(authzLinear);
  if (!authz) {
    throw new TRPCError({
      code: "PRECONDITION_FAILED",
      message: "linear_authz_required",
    });
  }

  const baseLinear = {
    ...linear,
    space,
    teamId: sanitize(linear.teamId),
    sessionId: sanitize(linear.sessionId),
    issueId: sanitize(linear.issueId),
    title: sanitize((linear as { title?: string })?.title),
    description: sanitize((linear as { description?: string })?.description),
  };

  if (baseLinear.sessionId) {
    const issueId = baseLinear.issueId ?? baseLinear.sessionId;
    return {
      linear: { ...baseLinear, issueId },
      ticket: issueId
        ? {
            issueId,
            sessionId: baseLinear.sessionId,
            issueUrl: (linear as { issueUrl?: string })?.issueUrl,
            created: false,
          }
        : undefined,
    };
  }

  if (baseLinear.issueId) {
    return {
      linear: { ...baseLinear, sessionId: baseLinear.issueId },
      ticket: {
        issueId: baseLinear.issueId,
        sessionId: baseLinear.issueId,
        issueUrl: (linear as { issueUrl?: string })?.issueUrl,
        created: false,
      },
    };
  }

  const teamId = baseLinear.teamId;
  if (!teamId) {
    throw new TRPCError({
      code: "PRECONDITION_FAILED",
      message: "linear_team_required",
    });
  }

  const title = buildTitle(requirement, baseLinear.title);
  const description = buildDescription(requirement, baseLinear.description);

  let result: Awaited<ReturnType<typeof toolTicket.execute>>;
  try {
    result = await toolTicket.execute({
      input: {
        space,
        action: "create",
        teamId,
        title,
        description,
        authz,
      },
    });
  } catch (error) {
    logger.warn("linear_ticket_creation_failed", {
      error: error instanceof Error ? error.message : String(error),
      space,
      teamId,
    });
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "linear_ticket_creation_failed",
    });
  }

  const issueId = sanitize(result.id);
  if (!issueId) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "linear_ticket_missing_id",
    });
  }

  return {
    linear: {
      ...baseLinear,
      sessionId: issueId,
      issueId,
    },
    ticket: {
      issueId,
      sessionId: issueId,
      issueUrl: sanitize(result.url),
      created: true,
    },
  };
}
