/**
 * Pattern: A learned template for workflow execution
 */
export interface Pattern {
  id: string;
  trigger: string;
  planTemplate: unknown;
  confidence: number;
}

/**
 * ClarificationQuestion: A question generated by the AI when intent is ambiguous
 */
export interface ClarificationQuestion {
  id: string;
  question: string;
  options?: string[]; // Multiple choice options
  required: boolean;
}

/**
 * Constraint: A limitation or requirement for the workflow
 */
export interface Constraint {
  type: string;
  value: string;
  reason?: string;
}

/**
 * WorkflowIntent: The structured representation of user intent
 */
export interface WorkflowIntent {
  id: string;
  description: string; // Natural language from user
  source: "voice" | "chat" | "api";
  userId: string;
  timestamp: Date;
  context: {
    projectId?: string; // Associated ALFRED project
    codebase?: string; // Repository context
    workspace?: string; // Workspace path
    existingPatterns: Pattern[]; // What ALFRED has learned
    constraints: Constraint[]; // Time, resources, complexity
  };
  ambiguity?: {
    score: number; // 0.0-1.0, higher = more ambiguous
    questions: ClarificationQuestion[];
  };
  multiIntent?: {
    split: boolean; // True if multiple intents detected
    intents: WorkflowIntent[]; // Split intents
  };
}
