---
- name: Ensure app directory exists
  file:
    path: "{{ alfred_app_dir }}"
    state: directory
    owner: "{{ alfred_user }}"
    group: "{{ alfred_group }}"
    mode: "0755"

- name: Template .env file
  template:
    src: env.j2
    dest: "{{ alfred_app_dir }}/.env"
    owner: "{{ alfred_user }}"
    group: "{{ alfred_group }}"
    mode: "0600"

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ alfred_app_dir }}/docker-compose.yml"
    owner: "{{ alfred_user }}"
    group: "{{ alfred_group }}"
    mode: "0644"

- name: Run docker compose up
  shell:
    cmd: "docker compose up -d"
    chdir: "{{ alfred_app_dir }}"
  become: yes
  become_user: "{{ alfred_user }}"
